version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: jobapp-db
    restart: always
    environment:
      MYSQL_DATABASE: jobapplication
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - jobapp_db_data:/var/lib/mysql
    networks:
      - jobapp-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jobapp-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/jobapplication
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - jobapp-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jobapp-frontend
    restart: always
    ports:
      - "3000:80"

    depends_on:
      - backend
    networks:
      - jobapp-net

volumes:
  jobapp_db_data:

networks:
  jobapp-net:
    driver: bridge
